const data = [
    {
        id: 1,
        name: "Island",
        url: 'https://a0.muscache.com/pictures/8e507f16-4943-4be9-b707-59bd38d56309.jpg',
        item: [
            {
                id: 1,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-1176955419486517899/original/83a47318-f3f6-4579-94d5-71523787ff11.jpeg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/miso/Hosting-1176955419486517899/original/1fc2607d-55cc-4f7a-871a-842c7eb3050f.jpeg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/miso/Hosting-1176955419486517899/original/396f3add-24d3-46be-8f98-c6e35c14262e.jpeg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/miso/Hosting-1176955419486517899/original/2a93e08c-d150-441c-bbcf-717991272f72.jpeg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/miso/Hosting-1176955419486517899/original/163fa6d6-054c-4025-a066-be75a42fc032.jpeg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Lohja, Finland",
                distance: "4854",
                date: "May 7-12",
                price: "291",
                rating: "5.0"
            },
            {
                id: 2,
                img1: "https://a0.muscache.com/im/pictures/fcae9cc4-d63a-4b24-9cec-59b0792456a9.jpg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/16f4c777-2587-4008-b755-86747c59b5e7.jpg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/f6bcdb88-8a26-4120-a934-7d192f0ad598.jpg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/5260040d-d1cd-447f-9e56-63b38330dadb.jpg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/1aa01811-c89c-4c2b-ae27-39ecc4ab040a.jpg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Anambas, Indonesia",
                distance: "2800",
                date: "Nov 16-21",
                price: "96",
                rating: "4.8"
            },
            {
                id: 3,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-54392028/original/82b8ac88-cca4-4e5b-84c6-aa7ac6eae5ca.jpeg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/miso/Hosting-54392028/original/dc201fe0-3935-45db-9a1a-8825ab9149cf.jpeg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/miso/Hosting-54392028/original/db1a814b-610e-45fc-8797-f65a7ce142c3.jpeg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/miso/Hosting-54392028/original/382f8eaa-333a-45e3-8bdb-504f93bcf831.jpeg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/miso/Hosting-54392028/original/99557880-bfd2-4c99-9cbd-74dc99c5ed81.jpeg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Alifu Dhaalu Atoll, Maldives",
                distance: "3116",
                date: "Nov 15-20",
                price: "895",
                rating: "4.0"
            },
            {
                id: 4,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-19705028/original/d144f08a-3cb5-4876-a897-88ee5df08261.jpeg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/89734365-33d1-4950-8560-61a06e9f66b7.jpg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/535cac65-0dea-4930-ad07-a14871723d97.jpg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/bddb84d5-09e5-4ff4-8cb2-a9f43f0c76d5.jpg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/cfeee8ff-207c-442f-b953-7a78ed2bc904.jpg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Munroe Island, India",
                distance: "1500",
                date: "Nov 17-22",
                price: "255",
                rating: "0.0"
            },
            {
                id: 5,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-972552508090480612/original/794ba670-eb98-47af-9883-03e4081ea5bb.jpeg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/miso/Hosting-964577283039581384/original/6f8bd7f5-1ec6-4ab4-9458-a28be2070935.jpeg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/miso/Hosting-964577283039581384/original/4b7d624d-7871-4301-b70a-0ee0668c0514.png?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/miso/Hosting-964577283039581384/original/89948277-b0d1-4d0c-a62f-1df8f06db1b5.png?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/miso/Hosting-964577283039581384/original/7a80a62a-11f0-4dc6-a55e-5811e8dbb474.png?im_w=720",
                mainTitle: "",
                description: "",
                title: "Fenfushi, Maldives",
                distance: "3126",
                date: "Nov 16-21",
                price: "400",
                rating: "5.0"
            },
            {
                id: 6,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-853512929423214729/original/f3d27f22-5175-467a-97fa-d040a08892cc.png?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/miso/Hosting-853512929423214729/original/d2731d23-980b-4fc1-8ccc-926d0e3f4eed.jpeg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/miso/Hosting-853512929423214729/original/be623727-4c78-44ca-a0c1-c448e5e0ccb8.jpeg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/miso/Hosting-853512929423214729/original/babc234f-04c7-40ee-963d-a3354c360194.jpeg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/miso/Hosting-853512929423214729/original/d8a6c21c-81c4-46a5-98cc-0bd7c92f6b4e.jpeg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Bathalaa Maldives",
                distance: "3061",
                date: "Nov 18-23",
                price: "390",
                rating: "5.0"
            },
            {
                id: 7,
                img1: "https://a0.muscache.com/im/pictures/61bd15e4-6594-4169-863e-11e4d74acb2e.jpg?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/8787fd74-1f00-4bfe-9eb7-ec32182a8b80.jpg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/c4f46895-29de-4571-9fe0-a0df5a39eb4b.jpg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/ec593870-4efa-4a82-866b-fd988f783baa.jpg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/cef7e4af-d8c6-4d6e-a3c0-2316197426e5.jpg?im_w=720",
                mainTitle: "",
                description: "",
                title: "Thailand",
                distance: "3588",
                date: "Mar 22-27",
                price: "220",
                rating: "4.9"
            },
            {
                id: 8,
                img1: "https://a0.muscache.com/im/pictures/miso/Hosting-852918482922249722/original/654156e3-f609-4e81-afc0-59ba12dd1ec2.png?im_w=960",
                img2: "https://a0.muscache.com/im/pictures/miso/Hosting-852918482922249722/original/74b12331-e010-41a0-bf91-90170b2b7b24.jpeg?im_w=720",
                img3: "https://a0.muscache.com/im/pictures/miso/Hosting-852918482922249722/original/3e102cff-cdae-4f9c-bc72-d352dcfe6304.jpeg?im_w=720",
                img4: "https://a0.muscache.com/im/pictures/miso/Hosting-852918482922249722/original/87fc1a22-1f00-42da-a600-ceb51313911f.jpeg?im_w=720",
                img5: "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6ODUyOTE4NDgyOTIyMjQ5NzIy/original/cfdef8e4-18e4-404c-ba16-7c8cd0b5e79a.png?im_w=720",
                mainTitle: "",
                description: "",
                title: "Male, Maldives",
                distance: "3031",
                date: "Nov 16-21",
                price: "600",
                rating: "5.0"
            },
        ]
    }, {
        id: 2,
        name: "Top Cities",
        url: 'https://a0.muscache.com/pictures/ed8b9e47-609b-44c2-9768-33e6a22eccb2.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "Sydney, Australia",
                distance: "10846",
                date: "Jan 19-24",
                price: "410",
                rating: "4.99"
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    }, {
        id: 3,
        name: "Amazing Views",
        url: 'https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    }, {
        id: 4,
        name: "Bed & breakfast",
        url: 'https://a0.muscache.com/pictures/5ed8f7c7-2e1f-43a8-9a39-4edfc81a3325.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 5,
        name: "Camping",
        url: 'https://a0.muscache.com/pictures/ca25c7f3-0d1f-432b-9efa-b9f5dc6d8770.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 6,
        name: "Cabins",
        url: 'https://a0.muscache.com/pictures/732edad8-3ae0-49a8-a451-29a8010dcc0c.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 7,
        name: "Rooms",
        url: 'https://a0.muscache.com/pictures/7630c83f-96a8-4232-9a10-0398661e2e6f.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 8,
        name: "Mansions",
        url: 'https://a0.muscache.com/pictures/78ba8486-6ba6-4a43-a56d-f556189193da.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 9,
        name: "Castles",
        url: 'https://a0.muscache.com/pictures/1b6a8b70-a3b6-48b5-88e1-2243d9172c06.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 10,
        name: "OMG!",
        url: 'https://a0.muscache.com/pictures/c5a4f6fc-c92c-4ae8-87dd-57f1ff1b89a6.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 11,
        name: "Trending",
        url: 'https://a0.muscache.com/pictures/3726d94b-534a-42b8-bca0-a0304d912260.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 12,
        name: "Arctic",
        url: 'https://a0.muscache.com/pictures/8b44f770-7156-4c7b-b4d3-d92549c8652f.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 13,
        name: "New",
        url: 'https://a0.muscache.com/pictures/c0fa9598-4e37-40f3-b734-4bd0e2377add.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 14,
        name: "Countryside",
        url: 'https://a0.muscache.com/pictures/6ad4bd95-f086-437d-97e3-14d12155ddfe.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 15,
        name: "Luxe",
        url: 'https://a0.muscache.com/pictures/c8e2ed05-c666-47b6-99fc-4cb6edcde6b4.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
    {
        id: 16,
        name: "Tropical",
        url: 'https://a0.muscache.com/pictures/ee9e2a40-ffac-4db9-9080-b351efc3cfc4.jpg',
        item: [
            {
                id: 1,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 2,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 3,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 4,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 5,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 6,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 7,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
            {
                id: 8,
                img1: "",
                img2: "",
                img3: "",
                img4: "",
                img5: "",
                mainTitle: "",
                description: "",
                title: "",
                distance: "",
                date: "",
                price: "",
                rating: ""
            },
        ]
    },
]

module.exports = data;